name: elp
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm ci, build and test
        run:
          npm install
          npm run build --if-present

      - name: Create deployment artifact
        run: tar -czf app.tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  web-deploy:
    needs: build
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: build
        path: build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        server-dir: /frontEnd